/* Generated by Yosys 0.56+125 (git sha1 d10fdc0ec, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

(* hdlname = "regfile" *)
(* top =  1  *)
(* src = "regfile.sv:16.1-37.10" *)
module regfile(clock, reset, val);
  (* src = "regfile.sv:17.10-17.15" *)
  input clock;
  wire clock;
  (* src = "regfile.sv:18.10-18.15" *)
  input reset;
  wire reset;
  (* src = "regfile.sv:19.17-19.20" *)
  output [31:0] val;
  wire [31:0] val;
  (* force_downto = 32'd1 *)
  (* src = "regfile.sv:32.21-32.35|/tools/yosys/202508/bin/../share/yosys/techmap.v:270.23-270.24" *)
  (* unused_bits = "1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] _00_;
  (* force_downto = 32'd1 *)
  (* src = "regfile.sv:33.23-33.39|/tools/yosys/202508/bin/../share/yosys/techmap.v:274.23-274.25" *)
  (* unused_bits = "3 4 5 6 7 8 9 10 11 12 13 14 15" *)
  wire [31:0] _01_;
  (* force_downto = 32'd1 *)
  (* src = "regfile.sv:33.23-33.39|/tools/yosys/202508/bin/../share/yosys/techmap.v:270.23-270.24" *)
  (* unused_bits = "4 5 6 7 8 9 10 11 12 13 14 15" *)
  wire [31:0] _02_;
  (* force_downto = 32'd1 *)
  (* src = "regfile.sv:33.23-33.39|/tools/yosys/202508/bin/../share/yosys/techmap.v:270.26-270.27" *)
  (* unused_bits = "4 5 6 7 8 9 10 11 12 13 14 15 16" *)
  wire [31:0] _03_;
  (* src = "regfile.sv:20.15-20.19" *)
  (* unused_bits = "1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 20 21 22 23 24 25 26 27 28 29 30 31" *)
  (* wiretype = "\\regfile_s" *)
  wire [63:0] regs;
  reg \regs_reg[16] ;
  (* src = "regfile.sv:25.3-36.6" *)
  always @(posedge clock, posedge reset)
    if (reset) \regs_reg[16]  <= 1'h0;
    else \regs_reg[16]  <= _02_[0];
  assign regs[16] = \regs_reg[16] ;
  reg \regs_reg[17] ;
  (* src = "regfile.sv:25.3-36.6" *)
  always @(posedge clock, posedge reset)
    if (reset) \regs_reg[17]  <= 1'h0;
    else \regs_reg[17]  <= _03_[1];
  assign regs[17] = \regs_reg[17] ;
  reg \regs_reg[18] ;
  (* src = "regfile.sv:25.3-36.6" *)
  always @(posedge clock, posedge reset)
    if (reset) \regs_reg[18]  <= 1'h0;
    else \regs_reg[18]  <= _03_[2];
  assign regs[18] = \regs_reg[18] ;
  reg \regs_reg[19] ;
  (* src = "regfile.sv:25.3-36.6" *)
  always @(posedge clock, posedge reset)
    if (reset) \regs_reg[19]  <= 1'h0;
    else \regs_reg[19]  <= _03_[3];
  assign regs[19] = \regs_reg[19] ;
  reg \regs_reg[0] ;
  (* src = "regfile.sv:25.3-36.6" *)
  always @(posedge clock, posedge reset)
    if (reset) \regs_reg[0]  <= 1'h0;
    else \regs_reg[0]  <= _00_[0];
  assign regs[0] = \regs_reg[0] ;
  assign _00_[0] = ~regs[0];
  assign _02_[0] = ~regs[16];
  assign _03_[1] = regs[17] ^(* src = "regfile.sv:33.23-33.39|/tools/yosys/202508/bin/../share/yosys/techmap.v:289.13-289.25" *)  regs[16];
  assign _03_[2] = regs[18] ^(* src = "regfile.sv:33.23-33.39|/tools/yosys/202508/bin/../share/yosys/techmap.v:289.13-289.25" *)  _01_[1];
  assign _03_[3] = regs[19] ^(* src = "regfile.sv:33.23-33.39|/tools/yosys/202508/bin/../share/yosys/techmap.v:289.13-289.25" *)  _01_[2];
  assign _01_[1] = regs[17] &(* src = "regfile.sv:33.23-33.39|/tools/yosys/202508/bin/../share/yosys/techmap.v:286.27-286.69|/tools/yosys/202508/bin/../share/yosys/techmap.v:240.19-240.41" *)  regs[16];
  assign _01_[2] = regs[18] &(* src = "regfile.sv:33.23-33.39|/tools/yosys/202508/bin/../share/yosys/techmap.v:286.27-286.69|/tools/yosys/202508/bin/../share/yosys/techmap.v:248.19-248.41" *)  _01_[1];
  assign _00_[31:1] = regs[31:1];
  assign { _01_[31:16], _01_[0] } = { 16'h0000, regs[16] };
  assign _02_[31:1] = { 16'h0000, regs[31:17] };
  assign { _03_[31:16], _03_[0] } = { 15'h0000, _01_[15], _02_[0] };
  assign regs[63:32] = 32'd0;
  assign val = { 28'h0000000, regs[19:17], regs[0] };
endmodule
