#****************************************************************************
# Copyright 2019-2025 Matthew Ballance and contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#****************************************************************************
"""Helper functions for constraint expressions.

These functions are used within @constraint decorated methods and are
parsed from AST - they are never actually executed.
"""
from typing import Any, Dict, List, Union, Tuple


class _ConstraintMarker:
    """Base class for constraint expression markers that are parsed from AST."""
    pass


class _ImpliesExpr(_ConstraintMarker):
    """Marker for implication constraint: antecedent -> consequent."""
    def __init__(self, antecedent: Any, consequent: Any):
        self.antecedent = antecedent
        self.consequent = consequent


class _DistExpr(_ConstraintMarker):
    """Marker for distribution constraint."""
    def __init__(self, var: Any, weights: Dict[Any, Union[int, Tuple[int, str]]]):
        self.var = var
        self.weights = weights


class _UniqueExpr(_ConstraintMarker):
    """Marker for uniqueness constraint."""
    def __init__(self, vars: List[Any]):
        self.vars = vars


class _SolveOrderExpr(_ConstraintMarker):
    """Marker for solve ordering constraint."""
    def __init__(self, *vars):
        self.vars = vars


def implies(antecedent: Any, consequent: Any) -> _ImpliesExpr:
    """Implication constraint: if antecedent is true, consequent must be true.
    
    This is logically equivalent to: (not antecedent) or consequent
    
    Example:
        @constraint
        def addr_implications(self):
            implies(self.addr_type == 0, self.addr < 16)
            implies(self.addr_type == 1, 16 <= self.addr < 128)
    
    Args:
        antecedent: Condition that triggers the implication
        consequent: Condition that must hold when antecedent is true
        
    Returns:
        ImpliesExpr marker (never actually executed)
    """
    return _ImpliesExpr(antecedent, consequent)


def dist(var: Any, weights: Dict[Any, Union[int, Tuple[int, str]]]) -> _DistExpr:
    """Distribution constraint: assign weights to values or ranges.
    
    Example:
        @constraint
        def type_distribution(self):
            dist(self.pkt_type, {
                0: 40,           # Type 0: weight 40
                1: 30,           # Type 1: weight 30
                2: 20,           # Type 2: weight 20
                3: 10            # Type 3: weight 10
            })
        
        @constraint
        def addr_distribution(self):
            dist(self.addr, {
                range(0, 16): (16, 'per_value'),      # 16 weight per value
                range(16, 128): (112, 'total'),       # 112 total weight
                range(128, 256): (128, 'per_value')   # 128 weight per value
            })
    
    Args:
        var: Variable to constrain
        weights: Dict mapping values/ranges to weights.
                 Values can be:
                 - int: absolute weight for discrete value
                 - tuple(int, str): (weight, 'per_value') or (weight, 'total')
        
    Returns:
        DistExpr marker (never actually executed)
    """
    return _DistExpr(var, weights)


def unique(vars: Union[List[Any], Any]) -> Union[_UniqueExpr, bool]:
    """Uniqueness constraint: all variables/elements must have different values.
    
    Can be used two ways:
    1. With list of scalar variables: unique([self.id1, self.id2, self.id3])
    2. With array field: unique(self.buffer) - all array elements must be distinct
    
    Example:
        @constraint
        def all_unique(self):
            unique([self.id1, self.id2, self.id3])
            
        @constraint  
        def unique_array(self):
            assert unique(self.buffer)  # All elements in buffer are unique
    
    Args:
        vars: List of variables or array field that must be unique
        
    Returns:
        UniqueExpr marker (never actually executed) or bool for type checking
    """
    if isinstance(vars, list):
        return _UniqueExpr(vars)
    # For array argument (in randomize_with context), return True as placeholder
    # The actual constraint is generated by IR parser
    return True


def sum(arr: Any) -> int:
    """Sum of all elements in an array.
    
    Example:
        @constraint
        def total_constraint(self):
            assert sum(self.values) == 100
            
        with randomize_with(obj):
            assert sum(obj.buffer) < 200
    
    Args:
        arr: Array field to sum
        
    Returns:
        Sum value (placeholder - actual computation done by IR parser)
    """
    # In randomize_with context, use Python's built-in sum
    # In @constraint context, this is never executed (parsed from AST)
    if hasattr(arr, '__iter__'):
        return __builtins__['sum'](arr)
    return 0


def ascending(arr: Any) -> bool:
    """Constraint that array elements are in strictly ascending order.
    
    Ensures: arr[i] < arr[i+1] for all valid i
    
    Example:
        @constraint
        def ordered(self):
            assert ascending(self.sequence)
            
        with randomize_with(obj):
            assert ascending(obj.values)
    
    Args:
        arr: Array field to constrain
        
    Returns:
        bool (placeholder - actual constraint generated by IR parser)
    """
    # In randomize_with context, check if actually ascending
    # In @constraint context, this is never executed
    if hasattr(arr, '__iter__'):
        arr_list = list(arr)
        return all(arr_list[i] < arr_list[i+1] for i in range(len(arr_list)-1))
    return True


def descending(arr: Any) -> bool:
    """Constraint that array elements are in strictly descending order.
    
    Ensures: arr[i] > arr[i+1] for all valid i
    
    Example:
        @constraint
        def ordered(self):
            assert descending(self.priorities)
            
        with randomize_with(obj):
            assert descending(obj.data)
    
    Args:
        arr: Array field to constrain
        
    Returns:
        bool (placeholder - actual constraint generated by IR parser)
    """
    # In randomize_with context, check if actually descending
    # In @constraint context, this is never executed
    if hasattr(arr, '__iter__'):
        arr_list = list(arr)
        return all(arr_list[i] > arr_list[i+1] for i in range(len(arr_list)-1))
    return True


def solve_order(*vars) -> _SolveOrderExpr:
    """Solve ordering constraint: variables should be solved in specified order.
    
    Example:
        @constraint
        def addr_data_relation(self):
            solve_order(self.addr, self.data)
            self.data == self.addr * 2
        
        @constraint
        def pipeline_order(self):
            solve_order(self.stage1, self.stage2, self.stage3)
    
    Args:
        *vars: Variables in solve order (first is solved first)
        
    Returns:
        SolveOrderExpr marker (never actually executed)
    """
    return _SolveOrderExpr(*vars)


# Export all public symbols
__all__ = [
    'implies',
    'dist',
    'unique',
    'sum',
    'ascending',
    'descending',
    'solve_order',
]
