name: CI
on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  ci-linux:
    uses: zuspec/zuspec-release/.github/workflows/zuspec-pybuild.yml@main
    with:
        version_dir: 'src/zuspec/dataclasses'
        build_universal: true
        build_docs: true
        build_llms_txt: true
        llms_pat: "${{ secrets.LLMS_PAT }}"

    secrets:
        PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}


